Service created successfully
Access token is valid.
Data successfully written to C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\50_companies\nifty50_wiki.pkl
Data successfully written to C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\50_companies\nifty50_kite_instruments.pkl
connected(1) to kite now
Waiting for 257.538231 seconds...
Time is now 2023-11-03 09:14:59.005780

----------------------------------Starting ticks----------------------------------
Nifty_previous_candles.csv: 2023-11-03 09:15:00,19241.0,nan,nan,19246.95,12345790,4407046.05,85.9032070202074
trade_log.csv: 2023-11-03 09:20:00,entry,long,19248.35,19286.8467,19229.101649999997,nan,6137.5
connected(2) to kite now
Time is now 2023-11-03 09:20:17.644825

----------------------------------Starting ticks----------------------------------
Nifty_previous_candles.csv: 2023-11-03 09:20:00,19248.35,nan,nan,19246.15,5593239,4606147.25,85.4808815273105
Nifty_previous_candles.csv: 2023-11-03 09:25:00,19245.95,nan,nan,19248.55,7101425,4869300.5,85.70788904369333
Nifty_previous_candles.csv: 2023-11-03 09:30:00,19248.6,nan,nan,19249.7,3606015,4947531.0,85.82227633541527
Nifty_previous_candles.csv: 2023-11-03 09:35:00,19249.75,nan,nan,19260.45,2796728,5002006.6,86.87941037636003
Nifty_previous_candles.csv: 2023-11-03 09:40:00,19260.45,nan,nan,19250.2,2857625,4927461.65,80.70065905323032
Nifty_previous_candles.csv: 2023-11-03 09:45:00,19249.65,nan,nan,19237.1,3493453,4928554.75,73.50556937519835
Nifty_previous_candles.csv: 2023-11-03 09:50:00,19237.65,nan,nan,19249.15,2065592,4865452.25,75.65566365643197
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 09:55:00,19249.15,nan,nan,19250.95,2066866,4807310.4,75.96938063189413
connected(3) to kite now
Time is now 2023-11-03 10:00:11.327608

----------------------------------Starting ticks----------------------------------
Nifty_previous_candles.csv: 2023-11-03 10:00:00,19250.75,nan,nan,19268.1,3705376,4258012.9,78.77577227871605
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 10:05:00,19268.25,nan,nan,19267.4,3543200,4318430.1,78.37345295302234
Nifty_previous_candles.csv: 2023-11-03 10:10:00,19267.65,nan,nan,19264.9,2773106,4321311.6,76.86363087058436
Nifty_previous_candles.csv: 2023-11-03 10:15:00,19264.85,nan,nan,19262.5,2348931,4259491.2,75.3626713071784
Nifty_previous_candles.csv: 2023-11-03 10:20:00,19262.95,nan,nan,19260.45,3721221,4254843.95,74.03283020554652
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 10:25:00,19258.85,nan,nan,19259.1,2436134,4164009.75,73.11780885726576
Nifty_previous_candles.csv: 2023-11-03 10:30:00,19259.55,nan,nan,19256.35,2274567,4069052.65,71.18764097615582
Nifty_previous_candles.csv: 2023-11-03 10:35:00,19256.7,nan,nan,19254.65,1721786,3909494.3,69.95818951139678
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 10:40:00,19254.35,nan,nan,19255.4,1830230,3769757.65,70.20269063684844
Nifty_previous_candles.csv: 2023-11-03 10:45:00,19253.45,nan,nan,19263.7,1576481,3595035.8,72.83737177455754
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 10:50:00,19263.75,nan,nan,19263.25,2312095,3508493.0,72.46327147653409
Nifty_previous_candles.csv: 2023-11-03 10:55:00,19263.55,nan,nan,19270.45,1927315,2987569.25,74.70210991635744
Nifty_previous_candles.csv: 2023-11-03 11:00:00,19270.55,nan,nan,19272.45,1388095,2777312.05,75.30278629554107
Nifty_previous_candles.csv: 2023-11-03 11:05:00,19272.05,nan,nan,19269.6,2101084,2527295.0,72.65536246158211
Nifty_previous_candles.csv: 2023-11-03 11:10:00,19269.5,nan,nan,19268.5,1397259,2416857.2,71.60892782025726
Nifty_previous_candles.csv: 2023-11-03 11:15:00,19268.7,nan,nan,19265.45,1987503,2376395.95,68.65624811710529
Nifty_previous_candles.csv: 2023-11-03 11:20:00,19265.65,nan,nan,19265.05,1826468,2324838.1,68.25873429538774
Nifty_previous_candles.csv: 2023-11-03 11:25:00,19264.95,nan,nan,19253.95,1830373,2241684.1,58.19013212724213
Nifty_previous_candles.csv: 2023-11-03 11:30:00,19252.35,nan,nan,19256.6,1564454,2216627.2,59.717809370114225
Nifty_previous_candles.csv: 2023-11-03 11:35:00,19256.95,nan,nan,19258.65,1681063,2197337.05,60.90777887316749
Nifty_previous_candles.csv: 2023-11-03 11:40:00,19259.3,nan,nan,19250.9,1997308,2111933.65,54.368866002362545
Nifty_previous_candles.csv: 2023-11-03 11:45:00,19250.45,nan,nan,19251.75,2130672,2041307.25,54.94024402298789
Nifty_previous_candles.csv: 2023-11-03 11:50:00,19250.1,nan,nan,19246.5,1809523,1993128.1,50.71614972402811
Nifty_previous_candles.csv: 2023-11-03 11:55:00,19247.35,nan,nan,19240.9,2514259,2001394.5,46.60042512577972
Nifty_previous_candles.csv: 2023-11-03 12:00:00,19241.3,nan,nan,19239.7,2128438,1921755.35,45.74376250637643
Nifty_previous_candles.csv: 2023-11-03 12:05:00,19239.6,nan,nan,19243.85,2008674,1900382.35,49.22041002630274
Nifty_previous_candles.csv: 2023-11-03 12:10:00,19243.25,nan,nan,19245.65,2412294,1907268.7,50.69612054586651
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 12:15:00,19245.3,nan,nan,19250.0,1970612,1919710.0,54.16293219076684
Nifty_previous_candles.csv: 2023-11-03 12:20:00,19248.9,nan,nan,19246.3,1450064,1900701.7,50.88545295455035
Nifty_previous_candles.csv: 2023-11-03 12:25:00,19245.85,nan,nan,19247.55,1178181,1880786.7,51.943447350144226
connected(4) to kite now
Time is now 2023-11-03 12:30:12.015875

----------------------------------Starting ticks----------------------------------
Nifty_previous_candles.csv: 2023-11-03 12:30:00,19246.9,nan,nan,19245.0,1298458,1830104.85,49.59631548935796
Nifty_previous_candles.csv: 2023-11-03 12:35:00,19244.6,nan,nan,19248.95,1592895,1813383.85,53.12936070263644
Nifty_previous_candles.csv: 2023-11-03 12:40:00,19248.95,nan,nan,19252.0,2609263,1874442.25,55.71085760681701
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 12:45:00,19251.15,nan,nan,19252.2,1678132,1853294.65,55.88244957741984
Nifty_previous_candles.csv: 2023-11-03 12:50:00,19252.05,nan,nan,19248.1,1624292,1864646.3,51.47923061058623
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 12:55:00,19248.65,nan,nan,19252.95,1355188,1833030.55,55.905351747587694
Nifty_previous_candles.csv: 2023-11-03 13:00:00,19253.55,nan,nan,19255.5,1672737,1825344.0,58.071025261741454
Nifty_previous_candles.csv: 2023-11-03 13:05:00,19255.1,nan,nan,19259.4,1592981,1813474.4,61.20898492659886
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 13:10:00,19258.0,nan,nan,19253.9,1528417,1811672.55,54.96189732266194
Nifty_previous_candles.csv: 2023-11-03 13:15:00,19254.0,nan,nan,19257.55,1532998,1804269.3,58.023727819150274
connected(5) to kite now
Time is now 2023-11-03 13:20:08.507678

----------------------------------Starting ticks----------------------------------
Nifty_previous_candles.csv: 2023-11-03 13:20:00,19256.3,nan,nan,19260.7,1253791,1767093.45,60.51831728737694
connected(6) to kite now
Time is now 2023-11-03 13:25:12.372337

----------------------------------Starting ticks----------------------------------
Nifty_previous_candles.csv: 2023-11-03 13:25:00,19260.2,nan,nan,19259.15,1509810,1736050.35,58.670657527502264
Nifty_previous_candles.csv: 2023-11-03 13:30:00,19259.05,nan,nan,19257.35,1233509,1707249.65,56.51287319791576
Nifty_previous_candles.csv: 2023-11-03 13:35:00,19256.6,nan,nan,19258.35,1221881,1642630.75,57.44915682315507
Nifty_previous_candles.csv: 2023-11-03 13:40:00,19258.55,nan,nan,19258.7,1636114,1618014.55,57.791685902096845
Nifty_previous_candles.csv: 2023-11-03 13:45:00,19258.4,nan,nan,19253.5,1677859,1601473.8,51.19754267830541
Nifty_previous_candles.csv: 2023-11-03 13:50:00,19252.15,nan,nan,19257.35,1327236,1547220.9,55.2672285379807
Nifty_previous_candles.csv: 2023-11-03 13:55:00,19256.4,nan,nan,19251.55,1448868,1521133.7,48.68108230157998
connected(7) to kite now
Time is now 2023-11-03 14:00:10.081356

----------------------------------Starting ticks----------------------------------
Nifty_previous_candles.csv: 2023-11-03 14:00:00,19251.45,nan,nan,19259.7,1492284,1523244.7,56.52170393840531
Nifty_previous_candles.csv: 2023-11-03 14:05:00,19258.5,nan,nan,19255.1,1657705,1547220.9,51.71877517205638
Nifty_previous_candles.csv: 2023-11-03 14:10:00,19253.85,nan,nan,19254.9,2222163,1593406.15,51.51381406738688
Nifty_previous_candles.csv: 2023-11-03 14:15:00,19254.0,nan,nan,19259.0,1688366,1598179.7,55.41461912781718
Nifty_previous_candles.csv: 2023-11-03 14:20:00,19258.15,nan,nan,19259.05,1715115,1553472.3,55.461677934178844
Nifty_previous_candles.csv: 2023-11-03 14:25:00,19258.35,nan,nan,19267.75,2109415,1575036.45,62.81594089520104
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 14:30:00,19267.05,nan,nan,19250.25,1853530,1586498.35,46.26672163504935
Nifty_previous_candles.csv: 2023-11-03 14:35:00,19249.65,nan,nan,19242.5,2820540,1659765.95,41.10229566005475
Nifty_previous_candles.csv: 2023-11-03 14:40:00,19240.9,nan,nan,19238.3,2271604,1689709.3,38.58842649728964
trade_log.csv: 2023-11-03 14:45:54,exit,reached stoploss,19229.0,nan,nan,-967.4999999999272,5170.000000000073
Nifty_previous_candles.csv: 2023-11-03 14:45:00,19237.05,nan,nan,19233.35,5609083,1890514.4,35.80867819437249
Nifty_previous_candles.csv: 2023-11-03 14:50:00,19232.95,nan,nan,19232.4,3248477,1976517.4,35.283361207795494
Nifty_previous_candles.csv: 2023-11-03 14:55:00,19233.15,nan,nan,19241.05,2155403,2007637.65,43.422100870000385
Nifty_previous_candles.csv: 2023-11-03 15:00:00,19241.9,nan,nan,19238.15,4048210,2147358.6,41.5361348728086
Error adding row to Google Sheet: [WinError 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Nifty-project\Nifty_Kite\googleSheetUtls.py", line 50, in add_row_to_sheet
    service.spreadsheets().values().append(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Administrator\Downloads\Nifty-project\venv\lib\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Nifty_previous_candles.csv: 2023-11-03 15:05:00,19238.5,nan,nan,19233.05,3692781,2256507.15,38.379131601596114
Nifty_previous_candles.csv: 2023-11-03 15:10:00,19233.95,nan,nan,19227.85,3885651,2389114.25,35.4228217190435
Nifty_previous_candles.csv: 2023-11-03 15:15:00,19228.35,nan,nan,19227.7,5164156,2586228.0,35.33826023915866
Nifty_previous_candles.csv: 2023-11-03 15:20:00,19227.35,nan,nan,19228.25,5242790,2766561.8,35.94209521484147
Nifty_previous_candles.csv: 2023-11-03 15:25:00,19229.35,nan,nan,19226.05,4024967,2883917.2,34.552171697014714
